### ISSUE TITLE
This is an awesome dialog system, I found in my use that I can't resolve double quotes nested, use \ escape is not working

### ISSUE THREAD

**Issue by Keeyuu** [sinbad/SUDS#11]
[set SpeakerName.someone "<TextLink style=\"blue_0\" type=\"a\" id=\"123\">someone</>"]   unable to parse
[set SpeakerName.someone "<TextLink style=\\"blue_0\\" type=\\"a\\" id=\\"123\\">someone</>"]   unable to parse,get \ not "

**Comment by Keeyuu** [comment]
This works well in the following situations  someone: something111111111<TextLink style="red_0" type="a" id="123">1234</>

**Comment by Keeyuu** [comment]
> Embedded quotes in strings are not supported right now, probably the best workaround is to use single quotes inside the string.

Single quotation marks can indeed be resolved but the engine can not recognize it, if I want to add the plugin to the double quotation mark support does it need to change a lot of places, is there any good way, I really want to add this plugin to my project

**Comment by sinbad** [comment]
Hmm, let me take a look to see how difficult it would be to add support for escaped quotes.

**Comment by sinbad** [comment]
OK I've managed to support escaped quotes without too much trouble: https://github.com/sinbad/SUDS/commit/0e07cf47022de819833de2b15aefccab54e19511

**Comment by Keeyuu** [comment]
> OK I've managed to support escaped quotes without too much trouble: [0e07cf4](https://github.com/sinbad/SUDS/commit/0e07cf47022de819833de2b15aefccab54e19511)

Thank you so much for your help
