### ISSUE TITLE
UE 5.4 TWeakObjectPtr can only be constructed with UObject types

### ISSUE THREAD

**Issue by Cordar** [sinbad/SUDS#14]
I have updated the plugin and now this error comes. I'm compiling using Rider and have migrated the project from 5.3 to 5.4. Any hints?

```
WeakObjectPtrTemplates.h(56): Error C2338 : static_assert failed: 'TWeakObjectPtr can only be constructed with UObject types'
0>SUDSScriptEdge.h(63) Reference  : Vea la referencia a la creación de una instancia de la función plantilla "TWeakObjectPtr<USUDSScriptNode,FWeakObjectPtr>::TWeakObjectPtr<USUDSScriptNode*,T>(U)" que se está compilando
0>        with
0>        [
0>            T=USUDSScriptNode *,
0>            U=USUDSScriptNode *
0>        ]
0>SUDSScriptEdge.h(63): Reference  : vea la primera referencia a "TWeakObjectPtr<USUDSScriptNode,FWeakObjectPtr>::TWeakObjectPtr" en "FSUDSScriptEdge::FSUDSScriptEdge"
```

Thank you in advance!

**Comment by sinbad** [comment]
SUDS will not work until 5.4.2 because in 5.4.0 Epic broke FText + StringTable support. The fix missed the merge for 5.4.1 but has now been merged so will be included in 5.4.2.

It's pointless upgrading until 5.4.2 because every single dialogue line returns "MISSING STRING TABLE ENTRY" because of this UE bug. They basically broke every project using StringTables.

**Comment by sinbad** [comment]
See https://github.com/sinbad/SUDS/issues/13. We will revisit final fixes for 5.4 once 5.4.2 is released  - although I have built it with 5.4.1 fine myself before realising they hadn't fixed the (runtime) bug with FText/StringTables.

**Comment by Cordar** [comment]
okay thanks!

**Comment by sinbad** [comment]
Today's 5.4.2 update fixes the issues. I've fixed the header inclusion ordering changes that affected UAT builds.

**Comment by Cmomnogmgg** [comment]
thanks! I am getting a weird error sometimes where it says Called CreateDialogue with invalid script, but it only happens sometimes in the packaged build (development or shipping does not seem to make a difference), not sure if it is related
