### ISSUE TITLE
Unreal 5.4.2 Project Missing Modules

### ISSUE THREAD

**Issue by rho-kk** [sinbad/SUDS#15]
Hey, I got this error after starting the project with activated Plugin.

The following modules are missing or built with a different engine version:

  SUDS
  SUDSEditor
  SUDSTest

Engine modules cannot be compiled at runtime. Please build through your IDE.

**Comment by sinbad** [comment]
SUDS is a C++ module and you need to actually build it, details are in the Readme. Basically your project has to be a C++ project and you build it with Visual Studio, or Rider etc. That's always been the case.

If you want a pre-built version where you don't have to do this then SUDS Pro is on the Marketplace, it also adds supplemental features beyond just dialogue running.

**Comment by rho-kk** [comment]
I got it, has to update my vs code because I run into build issues. 

Now I will check out your documentation. :)

Your stuff looks great! Thanks for your work
