### ISSUE TITLE
Text with random alternatives

### ISSUE THREAD

**Issue by Olaxan** [sinbad/SUDS#2]
I've written a few pieces of interactive fiction in the wonderful Inform7 language (www.inform7.com).
While that language is absolutely massive in scope and scale, there are a few "smaller" features that would be nice to see in SUDS, regarding randomness in the output.

Inform7 has an assortment of markup constructions for handling random/repeating text. They are listed in full here:
https://ganelson.github.io/inform-website/book/WI_5_7.html

The gist of it is that you construct sentences **[one of]** like this **[or]** in this manner **[or]** along these lines **[at random]**, and the output will be chosen before printing, depending on the specifier in the last bracket pair. 

Other convenient options to "_at random_" is "_cycling_", which goes through the set of options and repeats, and "_stopping_", which sticks to the last option after cycling once.

---
I think an easy in-text way of adding a bit of randomness to the text without having to go through variables and expressions could really help add flair to the dialogue, without disrupting the writing flow. This could be especially apt seeing how SUDS seems to be heavily text-focused (no voice-over data).

It's probably not a trivial thing, but I thought I'd launch the idea, since I've really enjoyed it in Inform.

**Comment by sinbad** [comment]
While you reproduce this right now using conditionals and an externally provided random variable, I can see how having it baked into the language is useful. 

In SUDS it's unlikely to ever happen within a line though, for simplicity all conditionals happens between entire lines. It just means a little duplication if there are shared elements, but arguably it's more readable that way.

Internally though, SUDS already has a construct that could do this. The "Select" node which picks conditional paths (ifs) does so based on a "first satisfied" basis, but could definitely do a random or cyclical choice instead. It would just be a case of coming up with the syntax to express it.

That said, I'm not sure when I'll get around to it, but I can see the utility for a future version.

**Comment by Olaxan** [comment]
Thanks for the reply!

A suggestion would be something along these lines:

```i7
[if  {ExampleVar}]
   [select]
      Robot: What's all this then?
   [or]
      Robot: What are you doing?
   [or]
      Robot: I can see you, you know!
   [random]
[else]
   [select]
      Robot: Hello.
   [or]
      Robot: I said hello.
   [or]
      Robot: That's enough of that.
      [goto Angry]
   [cycling]
[endif]
```

Nothing groundbreaking, but might get the job done.
Alternatively the mode up top and some uniform `endselect` clause at the bottom of the block.

You're definitely right, doing it in-line would almost certainly be more hassle than it's worth. Scopes are much better and more readable.

Anyway, it'd be fun to see this implemented, but I understand if it's not on the priority list!

**Comment by sinbad** [comment]
Cool, thanks for the suggestions. I can't promise when I'll get to it but it's a solid idea.

**Comment by sinbad** [comment]
Random lines are now implemented: https://github.com/sinbad/SUDS/blob/master/docs/RandomLines.md

Sequences are not supported, since they would require additional dialogue state which is more disruptive to the code. The random lines essentially generates if/elseif/else conditions, which depend on an internal generated int variable which is randomised every time that section of the dialogue is run.
